InternetKommunikation
4bHEL-Git-Gruppe/Schiffe-versenken pull request #3
Opened 2024-06-13 10:17 UTC by RobertSmith0202

Die Internetkommunikation wurde in zwei Klassen eingebettet. 
Weitere Infos in der README

2024-06-13 10:24 UTC, motaha18 submitted a review, later dismissed
ES Funktioniert.
README.md wurde nicht verändert.

Alles OK

2024-06-13 11:24 UTC, 0011011100110011 commented
falsche Readme.md, das was in dieser md drin is gehört in eine eigene für deine Dateien -> anderer Name!

Sonst wrscheinlich oki

2024-06-13 11:24 UTC, motaha18 commented
> falsche Readme.md, das was in dieser md drin is gehört in eine eigene für deine Dateien -> anderer Name!
> 
> Sonst wrscheinlich oki

BS

2024-06-13 12:14 UTC, motaha18 requested changes
Änderungen:
    - Könntest du bitte zuerst von dev pullen?
    - Bitte übernimm das README.md von dev und schreibe es nicht selbst.
    - Könntest du dein Entwickler-Tagebuch im Ordner Entwickler-Tagebücher ändern?
    - Bitte lösche Tagebuch_Robert.txt.
Vielen Dank!

2024-06-17 10:21 UTC, 0011011100110011 commented
überhaupt keine README.md in deinem Branch verwenden, bitte! 
sonst gibts Probleme wenn der Branch in dev gemerged wird!

2024-06-19 08:32 UTC, closed without merging